name: bdaya_fcm_handler
description: A new Flutter package project.
version: 0.0.2+2
author:
repository: https://github.com/Bdaya-Dev/fcm_handler

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^8.0.0-dev.14
  firebase_core: ^0.7.0
  get:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
