name: bdaya_fcm_handler
description: Helpers for FCM.
version: 3.1.0
repository: https://github.com/Bdaya-Dev/fcm_handler

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
