name: bdaya_fcm_handler
description: Helpers for FCM.
version: 0.1.0+5
repository: https://github.com/Bdaya-Dev/fcm_handler

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^9.0.0
  firebase_core: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
